#Where the data is located
input: "/archive2/camda/"
#Change the number of the files and these are all of the samples that will run through the pipeline

samples: [
  CAMDA20_MetaSUB_CSD16_BCN_001_1,  CAMDA20_MetaSUB_CSD16_BCN_020_1,
  CAMDA20_MetaSUB_CSD16_BCN_001_2,  CAMDA20_MetaSUB_CSD16_BCN_020_2,
  CAMDA20_MetaSUB_CSD16_BCN_002_1,  CAMDA20_MetaSUB_CSD16_BCN_021_1,
  CAMDA20_MetaSUB_CSD16_BCN_002_2,  CAMDA20_MetaSUB_CSD16_BCN_021_2,
  CAMDA20_MetaSUB_CSD16_BCN_003_1,  CAMDA20_MetaSUB_CSD16_BCN_022_1,
  CAMDA20_MetaSUB_CSD16_BCN_003_2,  CAMDA20_MetaSUB_CSD16_BCN_022_2,
  CAMDA20_MetaSUB_CSD16_BCN_004_1,  CAMDA20_MetaSUB_CSD16_BCN_023_1,
  CAMDA20_MetaSUB_CSD16_BCN_004_2,  CAMDA20_MetaSUB_CSD16_BCN_023_2,
  CAMDA20_MetaSUB_CSD16_BCN_005_1,  CAMDA20_MetaSUB_CSD16_BCN_024_1,
  CAMDA20_MetaSUB_CSD16_BCN_005_2,  CAMDA20_MetaSUB_CSD16_BCN_024_2,
  CAMDA20_MetaSUB_CSD16_BCN_006_1,  CAMDA20_MetaSUB_CSD16_BCN_025_1,
  CAMDA20_MetaSUB_CSD16_BCN_006_2,  CAMDA20_MetaSUB_CSD16_BCN_025_2,
  CAMDA20_MetaSUB_CSD16_BCN_007_1,  CAMDA20_MetaSUB_CSD16_BCN_026_1,
  CAMDA20_MetaSUB_CSD16_BCN_007_2,  CAMDA20_MetaSUB_CSD16_BCN_026_2,
  CAMDA20_MetaSUB_CSD16_BCN_008_1,  CAMDA20_MetaSUB_CSD16_BCN_027_1,
  CAMDA20_MetaSUB_CSD16_BCN_008_2,  CAMDA20_MetaSUB_CSD16_BCN_027_2,
  CAMDA20_MetaSUB_CSD16_BCN_009_1,  CAMDA20_MetaSUB_CSD16_BCN_028_1,
  CAMDA20_MetaSUB_CSD16_BCN_009_2,  CAMDA20_MetaSUB_CSD16_BCN_028_2,
  CAMDA20_MetaSUB_CSD16_BCN_010_1,  CAMDA20_MetaSUB_CSD16_BCN_029_1,
  CAMDA20_MetaSUB_CSD16_BCN_010_2,  CAMDA20_MetaSUB_CSD16_BCN_029_2,
  CAMDA20_MetaSUB_CSD16_BCN_011_1,  CAMDA20_MetaSUB_CSD16_BCN_030_1,
  CAMDA20_MetaSUB_CSD16_BCN_011_2,  CAMDA20_MetaSUB_CSD16_BCN_030_2,
  CAMDA20_MetaSUB_CSD16_BCN_012_1,  CAMDA20_MetaSUB_CSD16_BCN_031_1,
  CAMDA20_MetaSUB_CSD16_BCN_012_2,  CAMDA20_MetaSUB_CSD16_BCN_031_2,
  CAMDA20_MetaSUB_CSD16_BCN_013_1,  CAMDA20_MetaSUB_CSD16_BCN_032_1,
  CAMDA20_MetaSUB_CSD16_BCN_013_2,  CAMDA20_MetaSUB_CSD16_BCN_032_2,
  CAMDA20_MetaSUB_CSD16_BCN_014_1,  CAMDA20_MetaSUB_CSD16_BCN_033_1,
  CAMDA20_MetaSUB_CSD16_BCN_014_2,  CAMDA20_MetaSUB_CSD16_BCN_033_2,
  CAMDA20_MetaSUB_CSD16_BCN_015_1,  CAMDA20_MetaSUB_CSD16_BCN_034_1,
  CAMDA20_MetaSUB_CSD16_BCN_015_2,  CAMDA20_MetaSUB_CSD16_BCN_034_2,
  CAMDA20_MetaSUB_CSD16_BCN_016_1,  CAMDA20_MetaSUB_CSD16_BCN_035_1,
  CAMDA20_MetaSUB_CSD16_BCN_016_2,  CAMDA20_MetaSUB_CSD16_BCN_035_2,
  CAMDA20_MetaSUB_CSD16_BCN_017_1,  CAMDA20_MetaSUB_CSD16_BCN_036_1,
  CAMDA20_MetaSUB_CSD16_BCN_017_2,  CAMDA20_MetaSUB_CSD16_BCN_036_2,
  CAMDA20_MetaSUB_CSD16_BCN_018_1,  CAMDA20_MetaSUB_CSD16_BCN_037_1,
  CAMDA20_MetaSUB_CSD16_BCN_018_2,  CAMDA20_MetaSUB_CSD16_BCN_037_2,
  CAMDA20_MetaSUB_CSD16_BCN_019_1,  CAMDA20_MetaSUB_CSD16_BCN_038_1,
  CAMDA20_MetaSUB_CSD16_BCN_019_2,  CAMDA20_MetaSUB_CSD16_BCN_038_2, 
  CAMDA20_MetaSUB_CSD16_BER_014_1,  CAMDA20_MetaSUB_CSD16_BER_028_1,
  CAMDA20_MetaSUB_CSD16_BER_014_2,  CAMDA20_MetaSUB_CSD16_BER_028_2,
  CAMDA20_MetaSUB_CSD16_BER_001_1,  CAMDA20_MetaSUB_CSD16_BER_015_1,  CAMDA20_MetaSUB_CSD16_BER_029_1,
  CAMDA20_MetaSUB_CSD16_BER_001_2,  CAMDA20_MetaSUB_CSD16_BER_015_2,  CAMDA20_MetaSUB_CSD16_BER_029_2,
  CAMDA20_MetaSUB_CSD16_BER_002_1,  CAMDA20_MetaSUB_CSD16_BER_016_1,  CAMDA20_MetaSUB_CSD16_BER_030_1,
  CAMDA20_MetaSUB_CSD16_BER_002_2,  CAMDA20_MetaSUB_CSD16_BER_016_2,  CAMDA20_MetaSUB_CSD16_BER_030_2,
  CAMDA20_MetaSUB_CSD16_BER_003_1,  CAMDA20_MetaSUB_CSD16_BER_017_1,  CAMDA20_MetaSUB_CSD16_BER_031_1,
  CAMDA20_MetaSUB_CSD16_BER_003_2,  CAMDA20_MetaSUB_CSD16_BER_017_2,  CAMDA20_MetaSUB_CSD16_BER_031_2,
  CAMDA20_MetaSUB_CSD16_BER_004_1,  CAMDA20_MetaSUB_CSD16_BER_018_1,  CAMDA20_MetaSUB_CSD16_BER_032_1,
  CAMDA20_MetaSUB_CSD16_BER_004_2,  CAMDA20_MetaSUB_CSD16_BER_018_2,  CAMDA20_MetaSUB_CSD16_BER_032_2,
  CAMDA20_MetaSUB_CSD16_BER_005_1,  CAMDA20_MetaSUB_CSD16_BER_019_1,  CAMDA20_MetaSUB_CSD16_BER_033_1,
  CAMDA20_MetaSUB_CSD16_BER_005_2,  CAMDA20_MetaSUB_CSD16_BER_019_2,  CAMDA20_MetaSUB_CSD16_BER_033_2,
  CAMDA20_MetaSUB_CSD16_BER_006_1,  CAMDA20_MetaSUB_CSD16_BER_020_1,  CAMDA20_MetaSUB_CSD16_BER_034_1,
  CAMDA20_MetaSUB_CSD16_BER_006_2,  CAMDA20_MetaSUB_CSD16_BER_020_2,  CAMDA20_MetaSUB_CSD16_BER_034_2,
  CAMDA20_MetaSUB_CSD16_BER_007_1,  CAMDA20_MetaSUB_CSD16_BER_021_1,  CAMDA20_MetaSUB_CSD16_BER_035_1,
  CAMDA20_MetaSUB_CSD16_BER_007_2,  CAMDA20_MetaSUB_CSD16_BER_021_2,  CAMDA20_MetaSUB_CSD16_BER_035_2,
  CAMDA20_MetaSUB_CSD16_BER_008_1,  CAMDA20_MetaSUB_CSD16_BER_022_1,  CAMDA20_MetaSUB_CSD16_BER_036_1,
  CAMDA20_MetaSUB_CSD16_BER_008_2,  CAMDA20_MetaSUB_CSD16_BER_022_2,  CAMDA20_MetaSUB_CSD16_BER_036_2,
  CAMDA20_MetaSUB_CSD16_BER_009_1,  CAMDA20_MetaSUB_CSD16_BER_023_1,  CAMDA20_MetaSUB_CSD16_BER_037_1,
  CAMDA20_MetaSUB_CSD16_BER_009_2,  CAMDA20_MetaSUB_CSD16_BER_023_2,  CAMDA20_MetaSUB_CSD16_BER_037_2,
  CAMDA20_MetaSUB_CSD16_BER_010_1,  CAMDA20_MetaSUB_CSD16_BER_024_1,  CAMDA20_MetaSUB_CSD16_BER_038_1,
  CAMDA20_MetaSUB_CSD16_BER_010_2,  CAMDA20_MetaSUB_CSD16_BER_024_2,  CAMDA20_MetaSUB_CSD16_BER_038_2,
  CAMDA20_MetaSUB_CSD16_BER_011_1,  CAMDA20_MetaSUB_CSD16_BER_025_1,  CAMDA20_MetaSUB_CSD16_BER_039_1,
  CAMDA20_MetaSUB_CSD16_BER_011_2,  CAMDA20_MetaSUB_CSD16_BER_025_2,  CAMDA20_MetaSUB_CSD16_BER_039_2,
  CAMDA20_MetaSUB_CSD16_BER_012_1,  CAMDA20_MetaSUB_CSD16_BER_026_1,  CAMDA20_MetaSUB_CSD16_BER_040_1,
  CAMDA20_MetaSUB_CSD16_BER_012_2,  CAMDA20_MetaSUB_CSD16_BER_026_2,  CAMDA20_MetaSUB_CSD16_BER_040_2,
  CAMDA20_MetaSUB_CSD16_BER_013_1,  CAMDA20_MetaSUB_CSD16_BER_027_1,  CAMDA20_MetaSUB_CSD16_BER_041_1,
  CAMDA20_MetaSUB_CSD16_BER_013_2,  CAMDA20_MetaSUB_CSD16_BER_027_2,  CAMDA20_MetaSUB_CSD16_BER_041_2]
  



kmer_size: 31
groups_fl: "BCN_BER.pops"
